name: macOS-10.15_$(date:yyyyMMdd)$(rev:.r)_unstable

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    image_label: 'macOS Catalina'
    base_image_name: 'clean-macOS-10.15-380Gb-runner'
    template_path: 'templates/macOS-10.15.json'
    target_datastore: 'ds-local-Datastore-10.240.239.178 (1)'
